-- Nyaya schema (PostgreSQL 14+). Applied by `npm run db:init`, which runs on
-- every deploy: every statement here is idempotent, so add new tables/columns
-- in that style (IF NOT EXISTS, CREATE OR REPLACE) or as a file under
-- ./migrations for changes that can't be (see src/scripts/migrate.js).
--
-- Converted from the former MySQL schema.sql plus all of its migrations, the
-- four help-resource tables seed-help-resources.js used to create, and
-- legal_updates (see the note on it).
--
-- Conversion choices, so the existing app code keeps its assumptions:
--   * AUTO_INCREMENT      -> GENERATED BY DEFAULT AS IDENTITY ("BY DEFAULT" so
--                            rows copied from MySQL can keep their ids; reset
--                            the identity after a data copy - see the end).
--   * UNSIGNED            -> dropped (no Postgres equivalent); non-id columns
--                            that relied on it get a CHECK (>= 0).
--   * TINYINT(1)          -> SMALLINT with CHECK (IN (0, 1)), not BOOLEAN: the
--                            code compares `is_active = 1` and writes 0/1.
--   * DATETIME/TIMESTAMP  -> TIMESTAMPTZ (one unambiguous point in time; the
--                            code mixes UTC_TIMESTAMP() and JS Dates).
--   * ON UPDATE CURRENT_TIMESTAMP -> the set_updated_at() trigger below.
--   * KEY (...)           -> separate CREATE INDEX statements. InnoDB silently
--                            indexes every foreign key; Postgres does not, so
--                            any FK column without an index got one here.
--   * utf8mb4_unicode_ci  -> Postgres compares case-sensitively. The app
--                            already lowercases emails before storing and
--                            looking them up, so plain UNIQUE (email) matches.

-- ---------------------------------------------------------------------------
-- updated_at maintenance (replaces MySQL's ON UPDATE CURRENT_TIMESTAMP).
-- Like MySQL, it only bumps the timestamp when the row actually changed and
-- the UPDATE didn't set updated_at itself.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  IF NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at THEN
    NEW.updated_at := CURRENT_TIMESTAMP;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Users and sessions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  full_name VARCHAR(150) NOT NULL,
  email VARCHAR(191) DEFAULT NULL,
  phone VARCHAR(25) DEFAULT NULL,
  profession VARCHAR(120) DEFAULT NULL,
  avatar_url VARCHAR(500) DEFAULT NULL,
  password_hash VARCHAR(255) NOT NULL,
  firebase_uid VARCHAR(128) DEFAULT NULL,
  phone_verified SMALLINT NOT NULL DEFAULT 0 CHECK (phone_verified IN (0, 1)),
  password_reset_hash CHAR(64) DEFAULT NULL,
  password_reset_expires_at TIMESTAMPTZ DEFAULT NULL,
  password_reset_attempts INTEGER NOT NULL DEFAULT 0,
  email_verified SMALLINT NOT NULL DEFAULT 0 CHECK (email_verified IN (0, 1)),
  email_verification_hash CHAR(64) DEFAULT NULL,
  email_verification_expires_at TIMESTAMPTZ DEFAULT NULL,
  email_verification_attempts INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT uq_users_phone UNIQUE (phone),
  CONSTRAINT uq_users_firebase_uid UNIQUE (firebase_uid)
);
CREATE INDEX IF NOT EXISTS idx_users_status ON users (status);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  token_hash CHAR(64) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ DEFAULT NULL,
  last_used_at TIMESTAMPTZ DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
  CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash),
  CONSTRAINT fk_refresh_tokens_user
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);

-- ---------------------------------------------------------------------------
-- Content
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(120) NOT NULL,
  slug VARCHAR(150) NOT NULL,
  description TEXT DEFAULT NULL,
  image_url VARCHAR(500) DEFAULT NULL,
  is_active SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_categories PRIMARY KEY (id),
  CONSTRAINT uq_categories_slug UNIQUE (slug)
);
CREATE INDEX IF NOT EXISTS idx_categories_active ON categories (is_active);

CREATE TABLE IF NOT EXISTS articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  part VARCHAR(10) NOT NULL,
  part_title VARCHAR(200) NOT NULL,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(280) NOT NULL,
  article_range VARCHAR(60) NOT NULL,
  description TEXT NOT NULL,
  what_it_means TEXT DEFAULT NULL,
  why_it_matters TEXT DEFAULT NULL,
  key_features TEXT DEFAULT NULL,
  display_order INTEGER NOT NULL DEFAULT 1,
  is_active SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_articles PRIMARY KEY (id),
  CONSTRAINT uq_articles_slug UNIQUE (slug)
);
CREATE INDEX IF NOT EXISTS idx_articles_active ON articles (is_active);
CREATE INDEX IF NOT EXISTS idx_articles_order ON articles (display_order);

CREATE TABLE IF NOT EXISTS daily_questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  category VARCHAR(100) NOT NULL,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  CONSTRAINT pk_daily_questions PRIMARY KEY (id)
);
-- `answer` is now the explanation shown after a player picks an option.
ALTER TABLE daily_questions
  ADD COLUMN IF NOT EXISTS points_reward INTEGER NOT NULL DEFAULT 10 CHECK (points_reward >= 0);

-- A daily question is only served once it has options with exactly one correct
-- (enforced by the admin API, not here).
CREATE TABLE IF NOT EXISTS daily_question_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  daily_question_id INTEGER NOT NULL,
  option_text TEXT NOT NULL,
  is_correct SMALLINT NOT NULL DEFAULT 0 CHECK (is_correct IN (0, 1)),
  display_order INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT pk_daily_question_options PRIMARY KEY (id),
  CONSTRAINT fk_daily_question_options_question
    FOREIGN KEY (daily_question_id) REFERENCES daily_questions (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_daily_question_options_question ON daily_question_options (daily_question_id, display_order);

-- Which question is "today's" for everyone. Written on the first request of the
-- day, so the pick can't shift mid-day when admins add or edit questions.
CREATE TABLE IF NOT EXISTS daily_question_schedule (
  schedule_date DATE NOT NULL,
  daily_question_id INTEGER NOT NULL,
  CONSTRAINT pk_daily_question_schedule PRIMARY KEY (schedule_date),
  CONSTRAINT fk_daily_question_schedule_question
    FOREIGN KEY (daily_question_id) REFERENCES daily_questions (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_daily_question_schedule_question ON daily_question_schedule (daily_question_id);

-- One answer per player per day. The question/option references go NULL if an
-- admin deletes them, so the row (and the one-per-day guard) survives.
CREATE TABLE IF NOT EXISTS daily_question_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  attempt_date DATE NOT NULL,
  daily_question_id INTEGER DEFAULT NULL,
  selected_option_id BIGINT DEFAULT NULL,
  is_correct SMALLINT NOT NULL CHECK (is_correct IN (0, 1)),
  points_earned INTEGER NOT NULL DEFAULT 0,
  answered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_daily_question_attempts PRIMARY KEY (id),
  CONSTRAINT uq_daily_question_attempts_user_date UNIQUE (user_id, attempt_date),
  CONSTRAINT fk_daily_question_attempts_user
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_daily_question_attempts_question
    FOREIGN KEY (daily_question_id) REFERENCES daily_questions (id)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
  CONSTRAINT fk_daily_question_attempts_option
    FOREIGN KEY (selected_option_id) REFERENCES daily_question_options (id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_daily_question_attempts_question ON daily_question_attempts (daily_question_id);
CREATE INDEX IF NOT EXISTS idx_daily_question_attempts_option ON daily_question_attempts (selected_option_id);

-- legal_updates has no CREATE TABLE anywhere in the repo - it was created by
-- hand in MySQL. These columns are inferred from serializeLegalUpdate()
-- (src/utils/serializers.js) and the queries in src/routes/v1/legal-updates.js.
-- Check them against the real table (SHOW CREATE TABLE legal_updates;) before
-- relying on the sizes.
CREATE TABLE IF NOT EXISTS legal_updates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  category VARCHAR(30) NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary TEXT DEFAULT NULL,
  update_date DATE NOT NULL,
  source VARCHAR(255) DEFAULT NULL,
  image_url VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_legal_updates PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_legal_updates_category_date ON legal_updates (category, update_date);

CREATE TABLE IF NOT EXISTS translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  entity_type VARCHAR(32) NOT NULL,
  entity_id BIGINT NOT NULL,
  field_name VARCHAR(64) NOT NULL,
  lang_code VARCHAR(5) NOT NULL,
  translated_text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_translations PRIMARY KEY (id),
  CONSTRAINT uq_translations_entity_field_lang UNIQUE (entity_type, entity_id, field_name, lang_code)
);
CREATE INDEX IF NOT EXISTS idx_translations_lookup ON translations (entity_type, lang_code);

-- ---------------------------------------------------------------------------
-- Levels, quizzes and questions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS levels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  min_points INTEGER NOT NULL,
  max_points INTEGER NOT NULL,
  badge_icon VARCHAR(255) DEFAULT NULL,
  reward_description TEXT DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_levels PRIMARY KEY (id),
  CONSTRAINT uq_levels_code UNIQUE (code)
);
CREATE INDEX IF NOT EXISTS idx_levels_points ON levels (min_points, max_points);

-- level_id comes from migration 0001; MySQL's schema.sql doesn't declare it.
CREATE TABLE IF NOT EXISTS quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  category_id BIGINT NOT NULL,
  title VARCHAR(180) NOT NULL,
  slug VARCHAR(180) NOT NULL,
  description TEXT DEFAULT NULL,
  image_url VARCHAR(500) DEFAULT NULL,
  difficulty_level VARCHAR(30) NOT NULL DEFAULT 'medium',
  total_questions INTEGER NOT NULL DEFAULT 0,
  time_limit_seconds INTEGER DEFAULT NULL,
  passing_score NUMERIC(8,2) NOT NULL DEFAULT 0.00,
  level_id BIGINT DEFAULT NULL,
  is_active SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_quizzes PRIMARY KEY (id),
  CONSTRAINT uq_quizzes_slug UNIQUE (slug),
  CONSTRAINT fk_quizzes_category
    FOREIGN KEY (category_id) REFERENCES categories (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_quizzes_level
    FOREIGN KEY (level_id) REFERENCES levels (id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_quizzes_category_id ON quizzes (category_id);
CREATE INDEX IF NOT EXISTS idx_quizzes_level_id ON quizzes (level_id);
CREATE INDEX IF NOT EXISTS idx_quizzes_active ON quizzes (is_active);

CREATE TABLE IF NOT EXISTS questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  quiz_id BIGINT NOT NULL,
  question_text TEXT NOT NULL,
  question_type VARCHAR(30) NOT NULL DEFAULT 'single_choice',
  explanation TEXT DEFAULT NULL,
  difficulty_level VARCHAR(30) NOT NULL DEFAULT 'medium',
  points_reward INTEGER NOT NULL DEFAULT 0,
  negative_points INTEGER NOT NULL DEFAULT 0,
  display_order INTEGER NOT NULL DEFAULT 1,
  is_active SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_questions PRIMARY KEY (id),
  CONSTRAINT fk_questions_quiz
    FOREIGN KEY (quiz_id) REFERENCES quizzes (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_questions_quiz_id ON questions (quiz_id);
CREATE INDEX IF NOT EXISTS idx_questions_display_order ON questions (quiz_id, display_order);
CREATE INDEX IF NOT EXISTS idx_questions_active ON questions (is_active);

CREATE TABLE IF NOT EXISTS question_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  question_id BIGINT NOT NULL,
  option_text TEXT NOT NULL,
  is_correct SMALLINT NOT NULL DEFAULT 0 CHECK (is_correct IN (0, 1)),
  display_order INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_question_options PRIMARY KEY (id),
  CONSTRAINT fk_question_options_question
    FOREIGN KEY (question_id) REFERENCES questions (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_question_options_question_id ON question_options (question_id);
CREATE INDEX IF NOT EXISTS idx_question_options_order ON question_options (question_id, display_order);

-- ---------------------------------------------------------------------------
-- Quiz play
-- ---------------------------------------------------------------------------
-- quiz_id is nullable for practice-mode attempts (migration 0006).
CREATE TABLE IF NOT EXISTS quiz_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  quiz_id BIGINT DEFAULT NULL,
  started_at TIMESTAMPTZ NOT NULL,
  submitted_at TIMESTAMPTZ DEFAULT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'in_progress',
  total_questions INTEGER NOT NULL DEFAULT 0,
  answered_questions INTEGER NOT NULL DEFAULT 0,
  correct_answers INTEGER NOT NULL DEFAULT 0,
  wrong_answers INTEGER NOT NULL DEFAULT 0,
  skipped_answers INTEGER NOT NULL DEFAULT 0,
  total_score NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  total_points_earned INTEGER NOT NULL DEFAULT 0,
  completed_in_seconds INTEGER DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_quiz_attempts PRIMARY KEY (id),
  CONSTRAINT fk_quiz_attempts_user
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_quiz_attempts_quiz
    FOREIGN KEY (quiz_id) REFERENCES quizzes (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_quiz_attempts_user_id ON quiz_attempts (user_id);
CREATE INDEX IF NOT EXISTS idx_quiz_attempts_quiz_id ON quiz_attempts (quiz_id);
CREATE INDEX IF NOT EXISTS idx_quiz_attempts_status ON quiz_attempts (status);
CREATE INDEX IF NOT EXISTS idx_quiz_attempts_started_at ON quiz_attempts (started_at);

CREATE TABLE IF NOT EXISTS quiz_attempt_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  quiz_attempt_id BIGINT NOT NULL,
  question_id BIGINT NOT NULL,
  display_order INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT pk_quiz_attempt_questions PRIMARY KEY (id),
  CONSTRAINT uq_quiz_attempt_questions_attempt_question UNIQUE (quiz_attempt_id, question_id),
  CONSTRAINT fk_quiz_attempt_questions_attempt
    FOREIGN KEY (quiz_attempt_id) REFERENCES quiz_attempts (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_quiz_attempt_questions_question
    FOREIGN KEY (question_id) REFERENCES questions (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_quiz_attempt_questions_question_id ON quiz_attempt_questions (question_id);

CREATE TABLE IF NOT EXISTS question_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  quiz_attempt_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  question_id BIGINT NOT NULL,
  selected_option_id BIGINT DEFAULT NULL,
  is_correct SMALLINT NOT NULL DEFAULT 0 CHECK (is_correct IN (0, 1)),
  points_earned INTEGER NOT NULL DEFAULT 0,
  answered_at TIMESTAMPTZ NOT NULL,
  response_time_ms INTEGER DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_question_attempts PRIMARY KEY (id),
  CONSTRAINT fk_question_attempts_quiz_attempt
    FOREIGN KEY (quiz_attempt_id) REFERENCES quiz_attempts (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_question_attempts_user
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_question_attempts_question
    FOREIGN KEY (question_id) REFERENCES questions (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_question_attempts_selected_option
    FOREIGN KEY (selected_option_id) REFERENCES question_options (id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_question_attempts_quiz_attempt_id ON question_attempts (quiz_attempt_id);
CREATE INDEX IF NOT EXISTS idx_question_attempts_user_id ON question_attempts (user_id);
CREATE INDEX IF NOT EXISTS idx_question_attempts_question_id ON question_attempts (question_id);
CREATE INDEX IF NOT EXISTS idx_question_attempts_selected_option_id ON question_attempts (selected_option_id);

CREATE TABLE IF NOT EXISTS practice_settings (
  difficulty_level VARCHAR(30) NOT NULL,
  question_count INTEGER NOT NULL DEFAULT 10,
  is_enabled SMALLINT NOT NULL DEFAULT 1 CHECK (is_enabled IN (0, 1)),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_practice_settings PRIMARY KEY (difficulty_level)
);

-- Default rows, as inserted by migration 0006.
INSERT INTO practice_settings (difficulty_level, question_count, is_enabled)
VALUES ('easy', 10, 1), ('medium', 10, 1), ('hard', 10, 1)
ON CONFLICT (difficulty_level) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Progress, points and achievements
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS point_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  source_type VARCHAR(50) NOT NULL,
  source_id BIGINT DEFAULT NULL,
  points_delta INTEGER NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_point_transactions PRIMARY KEY (id),
  CONSTRAINT fk_point_transactions_user
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_point_transactions_user_id ON point_transactions (user_id);
CREATE INDEX IF NOT EXISTS idx_point_transactions_source ON point_transactions (source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_point_transactions_created_at ON point_transactions (created_at);

CREATE TABLE IF NOT EXISTS user_progress (
  user_id BIGINT NOT NULL,
  total_points INTEGER NOT NULL DEFAULT 0,
  current_level_id BIGINT DEFAULT NULL,
  total_quizzes_attempted INTEGER NOT NULL DEFAULT 0,
  total_quizzes_completed INTEGER NOT NULL DEFAULT 0,
  total_questions_answered INTEGER NOT NULL DEFAULT 0,
  total_correct_answers INTEGER NOT NULL DEFAULT 0,
  total_wrong_answers INTEGER NOT NULL DEFAULT 0,
  accuracy_percentage NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  credits INTEGER NOT NULL DEFAULT 100,
  credits_updated_at TIMESTAMPTZ DEFAULT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_user_progress PRIMARY KEY (user_id),
  CONSTRAINT fk_user_progress_user
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_user_progress_level
    FOREIGN KEY (current_level_id) REFERENCES levels (id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_user_progress_level_id ON user_progress (current_level_id);

CREATE TABLE IF NOT EXISTS user_streaks (
  user_id BIGINT NOT NULL,
  current_streak INTEGER NOT NULL DEFAULT 0,
  max_streak INTEGER NOT NULL DEFAULT 0,
  last_activity_date DATE DEFAULT NULL,
  streak_start_date DATE DEFAULT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_user_streaks PRIMARY KEY (user_id),
  CONSTRAINT fk_user_streaks_user
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS achievements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  code VARCHAR(60) NOT NULL,
  title VARCHAR(150) NOT NULL,
  description TEXT DEFAULT NULL,
  achievement_type VARCHAR(50) NOT NULL,
  target_value INTEGER NOT NULL,
  reward_points INTEGER NOT NULL DEFAULT 0,
  is_active SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_achievements PRIMARY KEY (id),
  CONSTRAINT uq_achievements_code UNIQUE (code)
);
CREATE INDEX IF NOT EXISTS idx_achievements_type ON achievements (achievement_type);
CREATE INDEX IF NOT EXISTS idx_achievements_active ON achievements (is_active);

CREATE TABLE IF NOT EXISTS user_achievements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  achievement_id BIGINT NOT NULL,
  unlocked_at TIMESTAMPTZ NOT NULL,
  reward_points INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_user_achievements PRIMARY KEY (id),
  CONSTRAINT uq_user_achievements_user_achievement UNIQUE (user_id, achievement_id),
  CONSTRAINT fk_user_achievements_user
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_user_achievements_achievement
    FOREIGN KEY (achievement_id) REFERENCES achievements (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_user_achievements_achievement_id ON user_achievements (achievement_id);

-- ---------------------------------------------------------------------------
-- Credits (Learning Journey)
-- ---------------------------------------------------------------------------
-- The Learning Journey's spendable "energy": every mutation (spend, refund,
-- penalty, reward, chest claim, regen) is server-computed and logged here so
-- a client can never hand itself credits by editing local state. A spend can
-- be refunded at most once, enforced by the unique key on
-- refund_of_transaction_id rather than trusting the client to ask only once.
CREATE TABLE IF NOT EXISTS credit_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  reason VARCHAR(40) NOT NULL,
  amount INTEGER NOT NULL,
  refunded SMALLINT NOT NULL DEFAULT 0 CHECK (refunded IN (0, 1)),
  refund_of_transaction_id BIGINT DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_credit_transactions PRIMARY KEY (id),
  CONSTRAINT uq_credit_transactions_refund_of UNIQUE (refund_of_transaction_id),
  CONSTRAINT fk_credit_transactions_user
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_credit_transactions_refund_of
    FOREIGN KEY (refund_of_transaction_id) REFERENCES credit_transactions (id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_credit_transactions_user_id ON credit_transactions (user_id);
CREATE INDEX IF NOT EXISTS idx_credit_transactions_user_reason_created
  ON credit_transactions (user_id, reason, created_at);

-- One-time credit chest claims, keyed so the same chest can't be opened
-- twice even if the client replays the request.
CREATE TABLE IF NOT EXISTS credit_chest_claims (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  chest_type VARCHAR(10) NOT NULL,
  chest_index INTEGER NOT NULL CHECK (chest_index >= 0),
  reward INTEGER NOT NULL,
  claimed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_credit_chest_claims PRIMARY KEY (id),
  CONSTRAINT uq_credit_chest_claims_user_chest UNIQUE (user_id, chest_type, chest_index),
  CONSTRAINT fk_credit_chest_claims_user
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- Support and admin
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS support_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  subject VARCHAR(150) NOT NULL,
  message TEXT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'open',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_support_requests PRIMARY KEY (id),
  CONSTRAINT fk_support_requests_user
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_support_requests_user_id ON support_requests (user_id);

CREATE TABLE IF NOT EXISTS admin_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  admin_user_id BIGINT NOT NULL,
  method VARCHAR(10) NOT NULL,
  path VARCHAR(500) NOT NULL,
  status_code SMALLINT NOT NULL CHECK (status_code >= 0),
  request_body TEXT DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_admin_audit_log PRIMARY KEY (id),
  CONSTRAINT fk_admin_audit_log_user
    FOREIGN KEY (admin_user_id) REFERENCES users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_admin_audit_log_admin_user_id ON admin_audit_log (admin_user_id);
CREATE INDEX IF NOT EXISTS idx_admin_audit_log_created_at ON admin_audit_log (created_at);

-- ---------------------------------------------------------------------------
-- Help resources (in MySQL these are created by seed-help-resources.js)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS indian_states (
  code VARCHAR(4) NOT NULL,
  name VARCHAR(80) NOT NULL,
  kind VARCHAR(20) NOT NULL DEFAULT 'state',
  CONSTRAINT pk_indian_states PRIMARY KEY (code),
  CONSTRAINT uq_indian_states_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS support_categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  slug VARCHAR(60) NOT NULL,
  name VARCHAR(80) NOT NULL,
  display_order INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT pk_support_categories PRIMARY KEY (id),
  CONSTRAINT uq_support_categories_slug UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS help_resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  state_code VARCHAR(4) NOT NULL DEFAULT 'IN',
  resource_name VARCHAR(160) NOT NULL,
  phone_number VARCHAR(40) DEFAULT NULL,
  toll_free VARCHAR(40) DEFAULT NULL,
  email VARCHAR(160) DEFAULT NULL,
  website_url VARCHAR(300) DEFAULT NULL,
  service_hours VARCHAR(80) DEFAULT NULL,
  availability VARCHAR(80) DEFAULT NULL,
  source_name VARCHAR(160) NOT NULL,
  source_url VARCHAR(300) NOT NULL,
  verification_status VARCHAR(30) NOT NULL DEFAULT 'needs_verification',
  last_verified_at TIMESTAMPTZ DEFAULT NULL,
  is_active SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  display_order INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_help_resources PRIMARY KEY (id),
  CONSTRAINT uq_help_resources_state_name UNIQUE (state_code, resource_name)
);
CREATE INDEX IF NOT EXISTS idx_help_resources_state ON help_resources (state_code, is_active);

CREATE TABLE IF NOT EXISTS help_resource_categories (
  resource_id BIGINT NOT NULL,
  category_id INTEGER NOT NULL,
  CONSTRAINT pk_help_resource_categories PRIMARY KEY (resource_id, category_id),
  CONSTRAINT fk_hrc_resource
    FOREIGN KEY (resource_id) REFERENCES help_resources (id)
    ON DELETE CASCADE,
  CONSTRAINT fk_hrc_category
    FOREIGN KEY (category_id) REFERENCES support_categories (id)
    ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_help_resource_categories_category_id ON help_resource_categories (category_id);

-- ---------------------------------------------------------------------------
-- updated_at triggers, one per table that has the column.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER trg_categories_updated_at BEFORE UPDATE ON categories
  FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER trg_articles_updated_at BEFORE UPDATE ON articles
  FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER trg_translations_updated_at BEFORE UPDATE ON translations
  FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER trg_levels_updated_at BEFORE UPDATE ON levels
  FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER trg_quizzes_updated_at BEFORE UPDATE ON quizzes
  FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER trg_questions_updated_at BEFORE UPDATE ON questions
  FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER trg_quiz_attempts_updated_at BEFORE UPDATE ON quiz_attempts
  FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER trg_practice_settings_updated_at BEFORE UPDATE ON practice_settings
  FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER trg_user_progress_updated_at BEFORE UPDATE ON user_progress
  FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER trg_user_streaks_updated_at BEFORE UPDATE ON user_streaks
  FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER trg_achievements_updated_at BEFORE UPDATE ON achievements
  FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER trg_help_resources_updated_at BEFORE UPDATE ON help_resources
  FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Moves every identity past the highest id already in its table, so rows
-- copied in from MySQL with their original ids don't collide with new
-- inserts. Only ever moves a sequence forward, so it is safe to run on every
-- deploy (db:init does) - it never hands out the id of a deleted row again.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  col record;
  seq text;
  max_id bigint;
  last_id bigint;
BEGIN
  FOR col IN
    SELECT table_name, column_name
    FROM information_schema.columns
    WHERE table_schema = current_schema() AND is_identity = 'YES'
  LOOP
    seq := pg_get_serial_sequence(quote_ident(col.table_name), col.column_name);
    EXECUTE format('SELECT MAX(%I) FROM %I', col.column_name, col.table_name) INTO max_id;
    EXECUTE format('SELECT last_value FROM %s', seq) INTO last_id;

    IF max_id IS NOT NULL AND max_id >= last_id THEN
      PERFORM setval(seq, max_id, true);
    END IF;
  END LOOP;
END;
$$;
